# Generated by Django 5.2.6 on 2025-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("pasos", models.TextField()),
                (
                    "palabras_clave",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
