# Generated by Django 5.2.6 on 2025-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantillaExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "archivo_plantilla",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="plantillas_excel/",
                        verbose_name="Archivo de Plantilla",
                    ),
                ),
                (
                    "imagen_vista_previa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imagenes_plantillas/",
                        verbose_name="Imagen de Vista Previa",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Excel",
                "verbose_name_plural": "Plantillas de Excel",
            },
        ),
    ]
