# Generated by Django 5.2.6 on 2025-09-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_plantillaexcel_creador"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillaexcel",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Precio"
            ),
        ),
    ]
