# Generated by Django 5.2.6 on 2025-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_alter_plantillaexcel_options_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillaexcel",
            name="downloads",
            field=models.PositiveIntegerField(default=0, verbose_name="Descargas"),
        ),
    ]
