# Generated by Django 5.2.6 on 2025-10-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_plantillaexcel_downloads"),
        ("produccion", "0013_producto_impuestos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoMarketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, verbose_name="Activo en Marketplace"
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Publicación"
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_producto",
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto en Marketplace",
                "verbose_name_plural": "Productos en Marketplace",
            },
        ),
    ]
