# Generated by Django 5.2.6 on 2025-10-27 17:48

from django.db import migrations


from django.db import migrations

def marcar_activos(apps, schema_editor):
   ProductoMarketplace = apps.get_model('marketplace', 'ProductoMarketplace')
   ProductoMarketplace.objects.all().update(activo=True)

class Migration(migrations.Migration):

   dependencies = [
       ('marketplace', '0006_productomarketplace'),
   ]

   operations = [
       migrations.RunPython(marcar_activos),
   ]
