# Generated by Django 5.2.6 on 2025-09-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_remove_mipyme_numero_rut_remove_mipyme_rfc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mipyme",
            name="correo",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
