# Generated by Django 5.2.6 on 2025-09-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0004_alter_mipyme_correo_alter_mipyme_numero_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("LECTURA", "Solo Lectura"),
                    ("EDITOR", "Editor"),
                    ("ADMIN", "Administrador"),
                    ("AGREGARPRODUCTO", "Agregar Producto"),
                ],
                default="LECTURA",
                max_length=50,
            ),
        ),
    ]
