# Generated by Django 5.2.6 on 2025-09-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mipyme",
            name="numero_rut",
        ),
        migrations.RemoveField(
            model_name="mipyme",
            name="rfc",
        ),
        migrations.AddField(
            model_name="mipyme",
            name="identificador_fiscal",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Identificador Fiscal (RFC, RUT, etc.)",
            ),
        ),
    ]
