# Generated by Django 5.2.6 on 2025-09-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_alter_mipyme_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mipyme",
            name="correo",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mipyme",
            name="numero_telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
