# Generated by Django 5.2.6 on 2025-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0005_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="es_creador_contenido",
            field=models.BooleanField(default=False),
        ),
    ]
