# Generated by Django 5.2.6 on 2025-09-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0006_usuario_es_creador_contenido"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorEconomico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sector Económico",
                "verbose_name_plural": "Sectores Económicos",
            },
        ),
        migrations.AddField(
            model_name="mipyme",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cuentas.sectoreconomico",
                verbose_name="Sector Económico",
            ),
        ),
    ]
