# Generated by Django 5.2.6 on 2025-09-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0008_estándaressector"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstándaresMipyme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso Mínimo (kg)",
                    ),
                ),
                (
                    "peso_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso Máximo (kg)",
                    ),
                ),
                (
                    "tamano_largo_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Largo Mínimo (cm)",
                    ),
                ),
                (
                    "tamano_largo_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Largo Máximo (cm)",
                    ),
                ),
                (
                    "tamano_ancho_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ancho Mínimo (cm)",
                    ),
                ),
                (
                    "tamano_ancho_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ancho Máximo (cm)",
                    ),
                ),
                (
                    "tamano_alto_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Alto Mínimo (cm)",
                    ),
                ),
                (
                    "tamano_alto_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Alto Máximo (cm)",
                    ),
                ),
                (
                    "presentacion_estandar",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Presentación Estándar",
                    ),
                ),
                (
                    "mipyme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estándares",
                        to="cuentas.mipyme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estándar de MIPYME",
                "verbose_name_plural": "Estándares de MIPYMEs",
            },
        ),
        migrations.DeleteModel(
            name="EstándaresSector",
        ),
    ]
