# Generated by Django 5.2.6 on 2025-09-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0009_estándaresmipyme_delete_estándaressector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EstándaresMipyme",
        ),
    ]
