# Generated by Django 5.2.6 on 2025-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0010_delete_estándaresmipyme"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
    ]
