# Generated by Django 5.2.6 on 2025-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0011_usuario_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos/",
                verbose_name="Logo de la Empresa",
            ),
        ),
    ]
