# Generated by Django 5.2.6 on 2025-09-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0012_mipyme_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="margen_desperdicio_predeterminado",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                max_digits=5,
                verbose_name="Margen de desperdicio por defecto (%)",
            ),
        ),
        migrations.AddField(
            model_name="mipyme",
            name="moneda_predeterminada",
            field=models.CharField(
                choices=[
                    ("USD", "Dólar estadounidense"),
                    ("EUR", "Euro"),
                    ("MXN", "Peso mexicano"),
                    ("COP", "Peso colombiano"),
                    ("PEN", "Sol peruano"),
                    ("CLP", "Peso chileno"),
                    ("ARS", "Peso argentino"),
                    ("UYU", "Peso uruguayo"),
                    ("PYG", "Guaraní paraguayo"),
                    ("BOB", "Boliviano"),
                    ("BRL", "Real brasileño"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Moneda predeterminada",
            ),
        ),
        migrations.AddField(
            model_name="mipyme",
            name="porcentaje_ganancia_predeterminado",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                max_digits=5,
                verbose_name="Porcentaje de ganancia por defecto (%)",
            ),
        ),
        migrations.AddField(
            model_name="mipyme",
            name="unidad_medida_predeterminada",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogramos"),
                    ("g", "Gramos"),
                    ("l", "Litros"),
                    ("ml", "Mililitros"),
                    ("un", "Unidades"),
                    ("m", "Metros"),
                    ("cm", "Centímetros"),
                    ("m2", "Metros cuadrados"),
                    ("m3", "Metros cúbicos"),
                ],
                default="kg",
                max_length=10,
                verbose_name="Unidad de medida predeterminada",
            ),
        ),
    ]
