# Generated by Django 5.2.6 on 2025-09-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0013_mipyme_margen_desperdicio_predeterminado_and_more"),
    ]

    operations = [
        # Primero cambiar el tipo de columna usando SQL directo
        migrations.RunSQL(
            """
            -- Cambiar el tipo de columna de text a jsonb y convertir datos existentes
            ALTER TABLE cuentas_mipyme
            ALTER COLUMN unidad_medida_predeterminada
            TYPE jsonb USING (
                CASE
                    WHEN unidad_medida_predeterminada IS NULL THEN '[]'::jsonb
                    WHEN unidad_medida_predeterminada = '' THEN '[]'::jsonb
                    ELSE json_build_array(unidad_medida_predeterminada)::jsonb
                END
            );
            """,
            reverse_sql="""
            -- Revertir: convertir de jsonb a text (tomar el primer elemento del array)
            ALTER TABLE cuentas_mipyme
            ALTER COLUMN unidad_medida_predeterminada
            TYPE varchar(10) USING (
                CASE
                    WHEN json_array_length(unidad_medida_predeterminada) > 0
                    THEN unidad_medida_predeterminada->>0
                    ELSE 'kg'
                END
            );
            """
        ),
        migrations.AlterField(
            model_name="mipyme",
            name="moneda_predeterminada",
            field=models.CharField(
                choices=[
                    ("USD", "Dólar estadounidense"),
                    ("NIO", "Córdoba nicaragüense"),
                    ("HNL", "Lempira hondureño"),
                    ("CRC", "Colón costarricense"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Moneda predeterminada",
            ),
        ),
        migrations.AlterField(
            model_name="mipyme",
            name="unidad_medida_predeterminada",
            field=models.JSONField(
                default=list,
                help_text="Selecciona las unidades de medida que utilizará la empresa",
                verbose_name="Unidades de medida predeterminadas",
            ),
        ),
    ]