# Generated by Django 5.2.6 on 2025-09-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0014_change_unidad_medida_to_jsonfield"),
        ("produccion", "0011_producto_porcentaje_ganancia"),  # Dependencia de produccion
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Convertir abreviaturas de unidades a IDs en el campo JSON
            UPDATE cuentas_mipyme
            SET unidad_medida_predeterminada = (
                SELECT json_agg(um.id)
                FROM produccion_unidadmedida um
                WHERE um.abreviatura = ANY(
                    SELECT jsonb_array_elements_text(unidad_medida_predeterminada)::text
                )
            )
            WHERE unidad_medida_predeterminada IS NOT NULL
            AND jsonb_array_length(unidad_medida_predeterminada) > 0;
            """,
            reverse_sql="""
            -- Revertir: convertir IDs de vuelta a abreviaturas
            UPDATE cuentas_mipyme
            SET unidad_medida_predeterminada = (
                SELECT json_agg(um.abreviatura)
                FROM produccion_unidadmedida um
                WHERE um.id::text = ANY(
                    SELECT jsonb_array_elements_text(unidad_medida_predeterminada)::text
                )
            )
            WHERE unidad_medida_predeterminada IS NOT NULL
            AND jsonb_array_length(unidad_medida_predeterminada) > 0;
            """
        ),
    ]
