# Generated by Django 5.2.6 on 2025-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0015_convert_unidad_abreviaturas_to_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="codigo_confirmacion",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Código de confirmación",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email_confirmado",
            field=models.BooleanField(default=False, verbose_name="Email confirmado"),
        ),
    ]
