# Generated by Django 5.2.6 on 2025-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0016_usuario_codigo_confirmacion_usuario_email_confirmado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mipyme",
            name="margen_desperdicio_predeterminado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Margen de desperdicio por defecto (%)",
            ),
        ),
        migrations.AlterField(
            model_name="mipyme",
            name="porcentaje_ganancia_predeterminado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Porcentaje de ganancia por defecto (%)",
            ),
        ),
    ]
