# Generated by Django 5.2.6 on 2025-10-02 06:33

from django.db import migrations

def update_predeterminado_values(apps, schema_editor):
    Mipyme = apps.get_model('cuentas', 'Mipyme')
    Mipyme.objects.all().update(
        porcentaje_ganancia_predeterminado=0.00,
        margen_desperdicio_predeterminado=0.00
    )

class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0017_alter_mipyme_margen_desperdicio_predeterminado_and_more"),
    ]

    operations = [
        migrations.RunPython(update_predeterminado_values),
    ]
