# Generated by Django 5.2.6 on 2025-10-04 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0018_auto_20251002_0633"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="propietario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mipymes_propias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
