# Generated by Django 5.2.6 on 2025-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0019_mipyme_propietario"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="mostrar_productos_en_marketplace",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar productos en Marketplace"
            ),
        ),
    ]
