# Generated by Django 5.2.6 on 2025-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0019_mipyme_propietario"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="tienda_visible",
            field=models.BooleanField(
                default=False,
                help_text="Activa esta opción para mostrar tus productos en la tienda pública.",
                verbose_name="Visible en Tienda",
            ),
        ),
    ]
