# Generated by Django 5.2.6 on 2025-12-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0020_mipyme_tienda_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="portada",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portadas/",
                verbose_name="Portada de la Empresa",
            ),
        ),
    ]
