# Generated by Django 5.2.6 on 2025-12-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0021_mipyme_portada"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="coordenadas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Coordenadas (Google Maps)",
            ),
        ),
        migrations.AddField(
            model_name="mipyme",
            name="descripcion",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Descripción de la Empresa",
            ),
        ),
        migrations.AddField(
            model_name="mipyme",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Dirección"
            ),
        ),
    ]
