# Generated by Django 5.2.6 on 2025-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0022_mipyme_coordenadas_mipyme_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mipyme",
            name="coordenadas",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Coordenadas (Google Maps)",
            ),
        ),
    ]
