# Generated by Django 5.2.6 on 2025-12-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0023_alter_mipyme_coordenadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="mipyme",
            name="mostrar_productos_en_marketplace",
            field=models.BooleanField(default=False),
        ),
    ]
