# Generated by Django 5.2.6 on 2025-09-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="costo_unitario",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="insumo",
            name="stock_actual",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_actual",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="formulacion",
            unique_together={("producto", "insumo")},
        ),
    ]
