# Generated by Django 5.2.6 on 2025-09-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0002_insumo_costo_unitario_insumo_stock_actual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
