# Generated by Django 5.2.6 on 2025-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0005_usuario_rol"),
        ("produccion", "0004_insumo_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulacion",
            name="porcentaje_desperdicio",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de este insumo que se pierde en el proceso (ej: 5 para un 5%)",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="Proceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "costo_por_hora",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo de mano de obra o máquina por hora",
                        max_digits=10,
                    ),
                ),
                (
                    "mipyme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cuentas.mipyme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasoDeProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo_en_minutos", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.producto",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.proceso",
                    ),
                ),
            ],
            options={
                "unique_together": {("producto", "proceso")},
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="procesos",
            field=models.ManyToManyField(
                related_name="productos",
                through="produccion.PasoDeProduccion",
                to="produccion.proceso",
            ),
        ),
    ]
