# Generated by Django 5.2.6 on 2025-09-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0003_alter_producto_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
