# Generated by Django 5.2.6 on 2025-09-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0005_formulacion_porcentaje_desperdicio_proceso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorEconomico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sector Económico",
                "verbose_name_plural": "Sectores Económicos",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="sectores",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="produccion.sectoreconomico"
            ),
        ),
    ]
