# Generated by Django 5.2.6 on 2025-09-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0006_sectoreconomico_producto_sectores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="sectores",
        ),
        migrations.AddField(
            model_name="producto",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="presentacion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Presentación"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tamano_alto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Alto (cm)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tamano_ancho",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ancho (cm)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tamano_largo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Largo (cm)",
            ),
        ),
        migrations.DeleteModel(
            name="SectorEconomico",
        ),
    ]
