# Generated by Django 5.2.6 on 2025-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "produccion",
            "0010_remove_venta_cantidad_remove_venta_precio_unitario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="porcentaje_ganancia",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Porcentaje de Ganancia (%)",
            ),
        ),
    ]
