# Generated by Django 5.2.6 on 2025-10-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0019_mipyme_propietario"),
        ("produccion", "0011_producto_porcentaje_ganancia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del impuesto, ej: IVA, DGI", max_length=100
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje del impuesto",
                        max_digits=5,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si el impuesto está activo"
                    ),
                ),
                (
                    "mipyme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos",
                        to="cuentas.mipyme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "unique_together": {("mipyme", "nombre")},
            },
        ),
    ]
