# Generated by Django 5.2.6 on 2025-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0012_impuesto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="impuestos",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="produccion.impuesto"
            ),
        ),
    ]
