# Generated by Django 5.2.6 on 2025-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0013_producto_impuestos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="productos/",
                verbose_name="Imagen del Producto",
            ),
        ),
    ]
