# Generated by Django 5.2.6 on 2025-10-27 17:39

from django.db import migrations

def poblar_productos(apps, schema_editor):
    Producto = apps.get_model('produccion', 'Producto')
    ProductoMarketplace = apps.get_model('marketplace', 'ProductoMarketplace')
    for producto in Producto.objects.all():
        ProductoMarketplace.objects.get_or_create(producto=producto)

class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0013_producto_impuestos"),
        ("marketplace", "0006_productomarketplace"),
    ]

    operations = [
        migrations.RunPython(poblar_productos),
    ]
