# Generated by Django 5.2.6 on 2025-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0014_poblar_productos_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos_imagenes/"
            ),
        ),
    ]
