# Generated by Django 5.2.6 on 2025-12-01 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0014_producto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="productos/adicionales/",
                        verbose_name="Imagen Adicional",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes_adicionales",
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Adicional de Producto",
                "verbose_name_plural": "Imágenes Adicionales de Productos",
                "ordering": ["orden"],
            },
        ),
    ]
