# Generated by Django 5.2.6 on 2025-12-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0015_productoimagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="disponible_en_api",
            field=models.BooleanField(
                default=True,
                help_text="Si está desactivado, este producto no aparecerá en la tienda pública ni en la API.",
                verbose_name="Disponible en Tienda/API",
            ),
        ),
    ]
